// Project data with detailed information
const projectsData = {
     'streamhub': {
        title: 'StreamHub',
        shortDesc: 'This application is a modern movie discovery that uses a free movie API. By integrating real-time data, the app ensures that users always have access to up-to-date information about the latest films.',
        heroImage: './images/Moivssss.jpeg',
        timeTaken: '1 month',
        teamSize: '1 developer',
        problem: 'I wanted to learn how to work with a third-party Movie API, implement user authentication, and manage data using MongoDB. Existing tutorials were too basic and did not demonstrate how these technologies work together in a real-world application.',
solution: 'Built a movie discovery platform that integrates with a real-time Movie API and includes user authentication with MongoDB for data storage. This project enabled fetching and displaying live movie data, implementing login functionality, and managing user-related information in a full-stack environment.',
        fullDesc: 'StreamHub is a modern movie discovery application that leverages a free movie API to provide users with comprehensive movie information. The app features movie search, detailed movie pages, trending movies, and personalized recommendations.',
        techStack: ['React', 'tailwind', 'MongoDB', 'Node.js'],
        githubUrl: 'https://github.com/maandaadivhaho10/MoviesApp',
        liveUrl: 'https://movies-app-bice-tau.vercel.app/',
        category: 'web ecommerce'
    },
    'edumaster': {
        title: 'EduMaster',
        shortDesc: 'Learning Management System with third-party library integration such as Chatboard and Gemini AI for enhanced user interaction.',
        heroImage: 'images/portfolio/portfolio-3.jpg',
        timeTaken: '2 months',
        teamSize: '1 developer',
        problem: 'Educational institutions require comprehensive learning management systems that facilitate course delivery, student engagement, and progress tracking.',
        solution: 'Developed a feature-rich LMS with integrated chat functionality, course management tools, student progress tracking, and interactive learning modules.',
        fullDesc: 'EduMaster is a comprehensive Learning Management System designed to enhance online education. The platform integrates third-party libraries for chat functionality and provides tools for course creation, student management, and interactive learning experiences.',
        techStack: ['React', 'Node.js',"gemini AI", "Chatboard"],
        githubUrl: 'https://github.com/maandaadivhaho10/Learning-Managment-system',
        liveUrl: 'https://maandaadivhaho10.github.io/Learning-Managment-system/',
        category: 'web'
    },

    'recipe-finder': {
        title: 'Recipe Finder',
        shortDesc: 'Build a client-side Recipe Finder that lets users search a small local dataset, view details, and favorite recipes.',
        heroImage: './images/recipeImg.jpeg',
        timeTaken: '1 week',
        teamSize: '1 developer',
        problem: 'People struggle to find quick, healthy recipes that match their dietary preferences and available ingredients. Existing recipe apps are often overwhelming with too many options.',
        solution: 'Developed an intuitive recipe finder with a clean interface, allowing users to search recipes by ingredients, cuisine type, and dietary restrictions. The app includes a favorites system for quick access to preferred recipes.',
        fullDesc: 'Recipe Finder is a React-based application that helps users discover and save recipes. The app features a comprehensive recipe database, advanced search filters, detailed recipe views with ingredients and instructions, and a personal favorites collection.',
        techStack: ['React', 'Tailwind CSS'],
        githubUrl: 'https://github.com/maandaadivhaho10/RecipeFinder',
        liveUrl: 'https://recipe-finder-rose-seven.vercel.app/',
        category: 'web ecommerce'
    }
,
    'stellarstock': {
        title: 'StellarStock',
        shortDesc: 'E-commerce web application that allows users to buy and sell products online. Built with React and Node.js for optimal performance.',
        heroImage: './images/pexels-solliefoto-298864.jpg',
        timeTaken: '2 months',
        teamSize: '1 developer',
        problem: 'Traditional e-commerce platforms often lack intuitive user interfaces and real-time inventory management. Small businesses struggle with complex systems that require extensive training and maintenance.',
        solution: 'Developed a modern, responsive e-commerce platform with a clean UI/UX design, real-time inventory tracking, and seamless payment integration. The application provides an intuitive dashboard for both buyers and sellers.',
        fullDesc: 'StellarStock is a comprehensive e-commerce solution built with React for the frontend and Node.js for the backend. The platform features user authentication, product catalog management, shopping cart functionality, and secure payment processing. The responsive design ensures optimal performance across all devices.',
        techStack: ['React', 'Node.js'],
        githubUrl: 'https://github.com/maandaadivhaho10/StellarStock2',
        liveUrl: 'https://stellar-stock2-7ums.vercel.app/',
        category: 'web ecommerce'
    },
    'student-management': {
        title: 'Student Management System',
        shortDesc: 'A full-stack web app that lets users add, edit, view, and delete student records, using MongoDB as backend storage.',
        heroImage: './images/schoolImages.jpeg',
        timeTaken: '2 week',
        teamSize: '1 developer',
        problem: 'Educational institutions need efficient ways to manage student data, track academic progress, and maintain records. Manual record-keeping is time-consuming and prone to errors.',
        solution: 'Created a comprehensive student management system with CRUD operations, allowing administrators to efficiently manage student information, grades, and academic records through an intuitive web interface.',
        fullDesc: 'This MERN stack application provides a complete solution for student data management. Features include student registration, profile management, academic record tracking, and administrative controls. The system uses MongoDB for reliable data storage and provides a responsive interface for easy access.',
        techStack: ['React', 'Node.js', 'MongoDB', 'TypeScript'],
        githubUrl: 'https://github.com/maandaadivhaho10/MernStudentApp',
        liveUrl: 'https://mern-student-app.vercel.app/',
        category: 'web ecommerce'
    },
    'extreme-service-delivery': {
        title: 'Extreme Service Delivery',
        shortDesc: 'Developed and deployed a highly scalable full stack system for a municipality platform, addressing challenges of communication between residents and municipalities.',
        heroImage: './images/municipal.jpg',
        timeTaken: '4 months',
        teamSize: '2 developers',
        problem: 'Municipalities face challenges in efficiently communicating with residents and managing service requests. Traditional communication methods are slow and ineffective.',
        solution: 'Built a comprehensive municipal service delivery platform that enables residents to submit service requests, track progress, and receive updates. The system includes administrative tools for municipality staff to manage and respond to requests.',
        fullDesc: 'Extreme Service Delivery is a full-stack application designed to improve communication between municipalities and residents. The platform features service request submission, progress tracking, notification systems, and administrative dashboards for efficient service management.',
        techStack: ['Kotlin', 'Android'],
        githubUrl: 'https://github.com/maandaadivhaho10/AndriodExD',
        liveUrl: '#',
        category: 'android'
    },
    'melula': {
        title: 'Aurastyle',
        shortDesc: 'I successfully created the Aurastyle using React and CSS. This project demonstrates my ability to make a website responsive.',
        heroImage: 'images/s3.jpg',
        timeTaken: '2 weeks',
        teamSize: '1 developer',
        problem: 'Businesses need professional, responsive websites that work seamlessly across all devices. Many small businesses lack the resources to create effective online presence.',
        solution: 'Developed a responsive website with modern design principles, ensuring optimal user experience across desktop, tablet, and mobile devices. The site features clean navigation, engaging content layout, and professional aesthetics.',
        fullDesc: 'Melula is a responsive website built with React and CSS, showcasing modern web development practices. The project demonstrates proficiency in responsive design, component-based architecture, and creating engaging user interfaces.',
        techStack: ['React', 'tailwind'],
        githubUrl: 'https://github.com/maandaadivhaho10/Asssessment1',
        liveUrl: 'https://asssessment1-8w8s.vercel.app/',
        category: 'web ecommerce'
    },
    'task-tracker': {
        title: 'Task Tracker',
        shortDesc: 'A simple client-side Task Tracker app that allows users to add tasks to a local dataset, view task details, and mark favorite tasks for quick access.',
        heroImage: './images/TackerApp.jpg',
        timeTaken: '2 weeks',
        teamSize: '1 developer',
        problem: 'Individuals and teams need efficient ways to organize and track their tasks. Many existing task management tools are overly complex or require subscriptions.',
        solution: 'Created a lightweight, user-friendly task tracking application with local storage, allowing users to create, edit, and organize tasks without the need for accounts or subscriptions.',
        fullDesc: 'Task Tracker provides a simple yet effective solution for personal task management. Users can create tasks with descriptions, due dates, and priority levels. The app features local storage for data persistence and an intuitive interface for managing daily tasks.',
        techStack: ['React', 'Tailwind CSS'],
        githubUrl: 'https://github.com/maandaadivhaho10/TaskApp/invitations',
        liveUrl: 'https://task-app-beta-beryl.vercel.app/',
        category: 'web ecommerce'
    },
   
};
